### ISSUE TITLE
botnix for freebsd 11

### ISSUE THREAD

**Issue by darksis** [braindigitalis/botnix#1]
hello i will try run botnix in freebsd version 11 and ubuntu 18 and what i get is that
Can't locate modules/core/background.pm in @INC (you may need to install the mod                                ules::core::background module) (@INC contains: /home/asher/perl5/lib/perl5/5.30.                                0/amd64-freebsd-thread-multi /home/asher/perl5/lib/perl5/5.30.0 /home/asher/perl                                5/lib/perl5/amd64-freebsd-thread-multi /home/asher/perl5/lib/perl5 /usr/local/li                                b/perl5/site_perl/mach/5.30 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/                                5.30/mach /usr/local/lib/perl5/5.30) at botnix line 68.
if i miss something i happy to know please

**Comment by braindigitalis** [comment]
Modern Perl removed "." from @INC which causes this error.

You can either do a git pull to fetch a newer botnix, where i've added ``use lib '.';`` to restore the old way of working, and if you find this issue in other programs you could follow the steps in this guide: https://perlmaven.com/removal-of-the-current-directory-from-inc-and-travis

Let me know if this fixes it for you :-)

**Comment by darksis** [comment]
ok i will try run botnix from two system on Freebsd 11.3 and ubuntu 18.04 and i told to you if this ok
