### ISSUE TITLE
add core command oper

### ISSUE THREAD

**Issue by darksis** [braindigitalis/botnix#2]
brain if this possible add more commands for a bot to for oper can to using with him for inspircd
thanks

**Comment by braindigitalis** [comment]
I'm sure i can add this easily.
Would you want it to auto oper and then have a set of commands to use the oper access, like autokills etc?

**Comment by darksis** [comment]
if this possible add in config botnix auto oper when is connect and addoper remove oper
command oper kill gline autokills zline remove zline remove gline sajoin sapart samode saquit and add oper level like 2 4 9 help oper netoper Admin oper
